### ISSUE TITLE
make generic landing page more generic

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-prayer-campaigns#31]
mostly copy and paste and remove specific stuff.

- default no porch
- wp admin option to enable generic porch in campaigns plugin, select from available?
- copy over the ui/display template. Getting the landing page running
- figure out how magiclink/landing page combo works.
- create the wp admin: campaigns settings, porch settings, translations.

## User Journey for setting up a campaign

Install the campaigns plugin
Go to the prayer campaigns admin page
on the campaign settings tab:
* choose a porch (defaults to none) {creates new tabs for porch management}
* type name of people and place praying for
* set other campaign specific stuff like social links, images etc.
on the porch settings tab:
* set other porch specific stuff like ...
* anything that has not been hoisted to the campaign settings level
on the translations tab:
* make any translations of porch specific text

## TODO

- [x] move cross porch settings into the campaign settings option
- [x] deal with other porch settings on a per porch basis
- [x] only show settings for fields that are relevant for the current porch
- [x] only save key value pairs in porch settings, not all the labels etc.
- [x] refactor porch settings changes into the porch settings class
- [x] save the field translations as a seperate action
- [x] load the field translations from the settings
- [x] make fixed ramadan sections of text be configurable in the settings
- [x] make a translations tab

**Comment by squigglybob** [comment]
Do we want the porches in this plugin to have the same translation namespace as the plugin or different? @corsacca

**Comment by corsacca** [comment]
same namespace.

**Comment by squigglybob** [comment]
done...
